apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
        - image: config-server:0.0.1
          name: config-server-app
          ports:
            - containerPort: 8080
          env:
            - name: "TZ"
              value: "Asia/Phnom_Penh"
            - name: "SPRING_PROFILES_ACTIVE"
              value: "container"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
