apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - image: registry:2.7
          name: registry
          ports:
            - containerPort: 5000
          env:
            - name: "TZ"
              value: "Asia/Phnom_Penh"
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "0.2"
