apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
kind: Endpoints
apiVersion: v1
metadata:
  name: registry-service
subsets:
  - addresses:
      - ip: 172.17.0.1
    ports:
      - port: 5000
