apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mssql-app
  template:
    metadata:
      labels:
        app: mssql-app
    spec:
      containers:
        - image: mcr.microsoft.com/mssql/server
          name: mssql-app
          ports:
            - containerPort: 1433
          env:
            - name: "TZ"
              value: "Asia/Phnom_Penh"
            - name: "ACCEPT_EULA"
              value: "Y"
            - name: "MSSQL_SA_PASSWORD"
              value: "M@Dem0Dotnet"
            - name: "MSSQL_PID"
              value: "Express"
          resources:
            limits:
              memory: "2G"
              cpu: "3"
